// com_github_jsbxyyx_mjar_Mjarencrypt.h
/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_github_jsbxyyx_mjar_Mjarencrypt */

#ifndef _Included_com_github_jsbxyyx_mjar_Mjarencrypt
#define _Included_com_github_jsbxyyx_mjar_Mjarencrypt
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_github_jsbxyyx_mjar_Mjarencrypt
     * Method:    encrypt
     * Signature: ([B)[B
     */
    JNIEXPORT jbyteArray JNICALL Java_com_github_jsbxyyx_mjar_Mjarencrypt_encrypt
      (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif